export function renderControlCenter(nonce: string): string {
  const safeNonce = nonce.replace(/[^A-Za-z0-9_-]/g, '');
  return '<!doctype html>' +
  '<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">' +
  '<title>Mecord Control Center</title>' +
  '<style nonce="' + safeNonce + '">' +
  ':root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#0b0d10;color:#eef1f5}' +
  '*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 15% 0%,#18212d 0,#0b0d10 42%)}' +
  'button,input,textarea{font:inherit}button{cursor:pointer}.shell{max-width:1440px;margin:auto;padding:24px}.top{display:flex;gap:16px;align-items:center;justify-content:space-between;margin-bottom:20px}' +
  '.brand{display:flex;align-items:center;gap:12px}.mark{width:38px;height:38px;border-radius:12px;background:linear-gradient(145deg,#8aa7ff,#4e68ff);display:grid;place-items:center;font-weight:800;color:#07101f;box-shadow:0 10px 35px #4e68ff33}' +
  'h1{font-size:20px;margin:0}.muted{color:#8e98a8;font-size:13px}.auth{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.input{background:#10151c;border:1px solid #26303d;color:#eef1f5;border-radius:10px;padding:9px 11px;outline:none;min-width:220px}.input:focus{border-color:#6e86ff;box-shadow:0 0 0 3px #6e86ff20}' +
  '.btn{border:1px solid #2c3745;background:#161d26;color:#eef1f5;border-radius:10px;padding:9px 12px}.btn:hover{background:#1c2632}.primary{background:#6178ff;border-color:#7186ff;color:white}.danger{border-color:#713b42;color:#ffb9bf}.warn{border-color:#725d31;color:#ffd88a}' +
  '.status{display:flex;align-items:center;gap:8px}.dot{width:8px;height:8px;border-radius:50%;background:#59616d}.dot.ok{background:#49d17d;box-shadow:0 0 16px #49d17d88}.grid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(320px,.9fr);gap:16px}' +
  '.panel{background:#0f141a;border:1px solid #202935;border-radius:16px;overflow:hidden;box-shadow:0 14px 40px #0004}.panelHead{padding:16px 18px;border-bottom:1px solid #202935;display:flex;align-items:center;justify-content:space-between;gap:12px}.panelHead h2{font-size:14px;margin:0;letter-spacing:.02em}.panelBody{padding:14px 16px}' +
  '.tabs{display:flex;gap:6px;padding:6px;background:#0a0e13;border-bottom:1px solid #202935}.tab{padding:8px 11px;border:0;border-radius:8px;background:transparent;color:#98a3b3}.tab.active{background:#18212b;color:#fff}.hidden{display:none!important}' +
  '.task{padding:13px;border:1px solid #222d3a;border-radius:12px;margin-bottom:9px;background:#111820}.task:hover{border-color:#34465a}.taskTop{display:flex;justify-content:space-between;gap:12px}.taskTitle{font-size:14px;font-weight:650;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.badge{font-size:11px;padding:4px 7px;border-radius:999px;background:#202a36;color:#b9c3d0}.badge.VERIFIED{background:#153522;color:#72e49c}.badge.FAILED,.badge.CANCELLED{background:#3c1d22;color:#ff969f}.badge.BLOCKED{background:#392e18;color:#ffd478}.badge.RUNNING{background:#182d4b;color:#8fb9ff}' +
  '.actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.small{padding:6px 8px;font-size:12px}.empty{padding:30px;text-align:center;color:#7e8998}.detail{white-space:pre-wrap;word-break:break-word;font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;background:#090d12;border:1px solid #202935;border-radius:10px;padding:12px;max-height:480px;overflow:auto}' +
  '.field{margin-bottom:11px}.field label{display:block;font-size:12px;color:#95a0af;margin-bottom:6px}.field textarea{width:100%;min-height:88px;resize:vertical}.field .input{width:100%;min-width:0}.two{display:grid;grid-template-columns:1fr 1fr;gap:10px}.event{padding:10px 0;border-bottom:1px solid #1c2530}.event:last-child{border:0}.eventTitle{font-size:12px;color:#d9e0e8}.eventMeta{font-size:11px;color:#798697;margin-top:4px}.device{padding:10px;border:1px solid #222d3a;border-radius:10px;margin-bottom:8px}.toast{position:fixed;right:20px;bottom:20px;max-width:420px;background:#151d27;border:1px solid #354458;border-radius:12px;padding:11px 14px;box-shadow:0 18px 50px #0008;z-index:10}.toast.bad{border-color:#704149;color:#ffc1c6}' +
  '@media(max-width:900px){.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.auth{justify-content:flex-start;width:100%}.auth .input{flex:1}.shell{padding:14px}.two{grid-template-columns:1fr}}' +
  '</style></head><body><main class="shell">' +
  '<header class="top"><div class="brand"><div class="mark">M</div><div><h1>Mecord Control Center</h1><div class="muted">Local autonomous runtime · authoritative task state</div></div></div>' +
  '<div class="auth"><input id="agentToken" class="input" type="password" autocomplete="off" placeholder="Agent token"><input id="recoveryToken" class="input" type="password" autocomplete="off" placeholder="Recovery token (approvals)"><button id="connect" class="btn primary">Connect</button><button id="refresh" class="btn">Refresh</button></div></header>' +
  '<div class="grid"><section class="panel"><div class="panelHead"><h2>Operations</h2><div class="status"><span id="statusDot" class="dot"></span><span id="statusText" class="muted">Disconnected</span></div></div>' +
  '<div class="tabs"><button class="tab active" data-tab="tasks">Tasks</button><button class="tab" data-tab="goals">New goal</button><button class="tab" data-tab="activity">Activity</button><button class="tab" data-tab="devices">Devices</button></div>' +
  '<div id="tasks" class="panelBody tabPage"><div id="taskList" class="empty">Connect to load tasks.</div></div>' +
  '<div id="goals" class="panelBody tabPage hidden"><div class="field"><label>Objective</label><input id="objective" class="input" placeholder="What should Mecord accomplish?"></div><div class="field"><label>Success conditions · one per line</label><textarea id="success" class="input" placeholder="Build passes&#10;Requested state is verified"></textarea></div><div class="field"><label>Goal JSON</label><textarea id="goalJson" class="input" spellcheck="false" placeholder=\'{"kind":"project-quality-gate","root":"C:\\\\path","checks":["lint","test","build"],"requireAll":true}\'></textarea></div><div class="actions"><button id="submitGoal" class="btn primary">Submit & run</button><button id="queueGoal" class="btn">Queue only</button></div></div>' +
  '<div id="activity" class="panelBody tabPage hidden"><div id="activityList" class="empty">No activity loaded.</div></div>' +
  '<div id="devices" class="panelBody tabPage hidden"><div id="deviceList" class="empty">No devices loaded.</div></div></section>' +
  '<aside class="panel"><div class="panelHead"><h2>Task detail</h2><span id="selectedState" class="badge">—</span></div><div class="panelBody"><div id="taskDetail" class="empty">Select a task to inspect its graph, records, evidence and failures.</div></div></aside></div></main><div id="toast" class="toast hidden"></div>' +
  '<script nonce="' + safeNonce + '">' +
  '(()=>{"use strict";let token="",selected="",poll=null;const $=id=>document.getElementById(id);' +
  'function toast(message,bad){const n=$("toast");n.textContent=message;n.className="toast"+(bad?" bad":"");clearTimeout(n._t);n._t=setTimeout(()=>n.classList.add("hidden"),4200)}' +
  'async function api(path,init){if(!token)throw new Error("Connect with the agent token first.");const opts=Object.assign({},init||{});opts.headers=Object.assign({},opts.headers||{},{"authorization":"Bearer "+token});if(opts.body&&!opts.headers["content-type"])opts.headers["content-type"]="application/json";const res=await fetch(path,opts);let body={};try{body=await res.json()}catch{}if(!res.ok)throw new Error((body.error&&body.error.code?body.error.code+": ":"")+(body.error&&body.error.message?body.error.message:"Request failed"));return body}' +
  'function node(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=String(text);return n}' +
  'function button(text,cls,fn){const b=node("button","btn small "+(cls||""),text);b.type="button";b.addEventListener("click",e=>{e.stopPropagation();fn()});return b}' +
  'function stateBadge(state){return node("span","badge "+state,state)}' +
  'async function loadTasks(){const data=await api("/v1/tasks?limit=100");const box=$("taskList");box.replaceChildren();if(!data.tasks||!data.tasks.length){box.append(node("div","empty","No tasks yet."));return}for(const task of data.tasks){const card=node("div","task");const top=node("div","taskTop");const title=node("div","taskTitle",task.userObjective||task.id);top.append(title,stateBadge(task.state));card.append(top,node("div","muted",(task.id||"")+" · "+(task.updatedAt||"")));const actions=node("div","actions");if(task.state==="PENDING")actions.append(button("Run","primary",()=>control(task.id,"run")));if(task.state==="RUNNING")actions.append(button("Pause","",()=>control(task.id,"pause")),button("Cancel","danger",()=>control(task.id,"cancel")));if(task.state==="PAUSED")actions.append(button("Resume","primary",()=>control(task.id,"resume")),button("Cancel","danger",()=>control(task.id,"cancel")));if(task.state==="BLOCKED")actions.append(button("Review approval","warn",()=>selectTask(task.id)));if(!["VERIFIED","FAILED","CANCELLED"].includes(task.state))actions.append(button("Cancel","danger",()=>control(task.id,"cancel")));card.append(actions);card.addEventListener("click",()=>selectTask(task.id));box.append(card)}}' +
  'async function selectTask(id){selected=id;const data=await api("/v1/tasks/"+encodeURIComponent(id));const task=data.task;$("selectedState").textContent=task.state;$("selectedState").className="badge "+task.state;const wrap=node("div");const actions=node("div","actions");if(task.state==="PENDING")actions.append(button("Run","primary",()=>control(id,"run")));if(task.state==="RUNNING")actions.append(button("Pause","",()=>control(id,"pause")));if(task.state==="PAUSED")actions.append(button("Resume","primary",()=>control(id,"resume")));if(task.state==="BLOCKED"){const record=(task.execution&&task.execution.records||[]).find(r=>r.state==="BLOCKED");if(record)actions.append(button("Approve & resume","warn",()=>approve(id,record.actionId)));}if(!["VERIFIED","FAILED","CANCELLED"].includes(task.state))actions.append(button("Cancel","danger",()=>control(id,"cancel")));wrap.append(actions);const pre=node("pre","detail",JSON.stringify(task,null,2));wrap.append(pre);$("taskDetail").replaceChildren(wrap)}' +
  'async function control(id,op){try{await api("/v1/tasks/"+encodeURIComponent(id)+"/"+op,{method:"POST",body:"{}"});await refresh();if(selected===id)await selectTask(id)}catch(e){toast(e.message,true)}}' +
  'async function approve(id,actionId){const recovery=$("recoveryToken").value.trim();if(!recovery){toast("Recovery token is required for explicit approval.",true);return}try{await api("/v1/tasks/"+encodeURIComponent(id)+"/resume",{method:"POST",headers:{"x-operator-recovery-token":recovery},body:JSON.stringify({approvedActionId:actionId})});await refresh();await selectTask(id)}catch(e){toast(e.message,true)}}' +
  'async function loadActivity(){const data=await api("/v1/activity?limit=100");const box=$("activityList");box.replaceChildren();if(!data.events||!data.events.length){box.append(node("div","empty","No activity recorded."));return}for(const ev of data.events.slice().reverse()){const row=node("div","event");row.append(node("div","eventTitle",(ev.capability||ev.type||"event")+" · "+(ev.result||ev.status||"")),node("div","eventMeta",(ev.timestamp||ev.at||"")+" "+(ev.target||"")));box.append(row)}}' +
  'async function loadDevices(){const data=await api("/v1/devices");const box=$("deviceList");box.replaceChildren();if(data.local){const d=node("div","device");d.append(node("div","taskTitle",data.local.deviceName||"Local device"),node("div","muted",data.local.deviceId||""));box.append(d)}for(const peer of data.peers||[]){const d=node("div","device");d.append(node("div","taskTitle",peer.deviceName||"Paired device"),node("div","muted",(peer.status||"")+" · "+(peer.deviceId||"")));box.append(d)}if(!data.local&&!(data.peers||[]).length)box.append(node("div","empty","No device identity configured."))}' +
  'async function refresh(){try{await Promise.all([loadTasks(),loadActivity(),loadDevices()]);$("statusDot").className="dot ok";$("statusText").textContent="Connected";if(selected)await selectTask(selected)}catch(e){$("statusDot").className="dot";$("statusText").textContent="Disconnected";toast(e.message,true)}}' +
  'async function submit(run){try{const objective=$("objective").value.trim();if(!objective)throw new Error("Objective is required.");const goal=JSON.parse($("goalJson").value);const success=$("success").value.split(/\\r?\\n/).map(x=>x.trim()).filter(Boolean);if(!success.length)throw new Error("At least one success condition is required.");const data=await api("/v1/goals",{method:"POST",body:JSON.stringify({objective,successConditions:success,goal,run})});toast(run?"Goal submitted and execution started.":"Goal queued.");await refresh();if(data.task&&data.task.id)await selectTask(data.task.id)}catch(e){toast(e.message,true)}}' +
  '$("connect").addEventListener("click",()=>{token=$("agentToken").value.trim();$("agentToken").value="";if(!token){toast("Agent token is required.",true);return}refresh();if(poll)clearInterval(poll);poll=setInterval(()=>{if(token)loadTasks().catch(()=>{})},2500)});$("refresh").addEventListener("click",refresh);$("submitGoal").addEventListener("click",()=>submit(true));$("queueGoal").addEventListener("click",()=>submit(false));' +
  'for(const tab of document.querySelectorAll(".tab"))tab.addEventListener("click",()=>{for(const t of document.querySelectorAll(".tab"))t.classList.toggle("active",t===tab);for(const page of document.querySelectorAll(".tabPage"))page.classList.toggle("hidden",page.id!==tab.dataset.tab)});' +
  'window.addEventListener("beforeunload",()=>{token="";$("recoveryToken").value=""});' +
  '})();</script></body></html>';
}
