import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const [shell, style, script] = await Promise.all([
  fs.readFile(path.join(root, 'src', 'shell.html'), 'utf8'),
  fs.readFile(path.join(root, 'src', 'styles.css'), 'utf8'),
  fs.readFile(path.join(root, 'src', 'app.js'), 'utf8')
]);

for (const marker of ['__MECORD_NONCE__','__MECORD_STYLE__','__MECORD_SCRIPT__']) {
  if (!shell.includes(marker)) throw new Error(`Control Center shell is missing ${marker}.`);
}
if (/localStorage|sessionStorage/.test(script)) throw new Error('Control Center must not persist authority tokens in browser storage.');
if (!shell.includes('role="tablist"') || !shell.includes('aria-live="polite"')) {
  throw new Error('Control Center accessibility landmarks are missing.');
}
if (!script.includes('/v1/control-center/approvals') || !script.includes('/v1/control-center/recovery')
  || !script.includes('/v1/control-center/onboarding') || !script.includes('/v1/control-center/diagnostics')) {
  throw new Error('Control Center is missing an R4 runtime-backed product surface.');
}

const template = shell
  .replace('__MECORD_STYLE__', style.trim())
  .replace('__MECORD_SCRIPT__', script.trim());

const generated = `// GENERATED by apps/control-center/scripts/build.mjs. Edit apps/control-center/src/* instead.\n` +
  `const CONTROL_CENTER_TEMPLATE = ${JSON.stringify(template)};\n\n` +
  `export function renderControlCenter(nonce: string): string {\n` +
  `  const safeNonce = nonce.replace(/[^A-Za-z0-9_-]/g, '');\n` +
  `  return CONTROL_CENTER_TEMPLATE.replaceAll('__MECORD_NONCE__', safeNonce);\n` +
  `}\n`;

await fs.writeFile(path.resolve(root, '..', 'local-agent', 'src', 'control-center.ts'), generated, 'utf8');
