(()=>{"use strict";
const state={token:"",recovery:"",view:"home",connected:false,onboardingStartedAt:0,onboardingCompletedSent:false,supportBundle:null};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(message,bad=false){const n=$("toast");n.textContent=message;n.className="toast"+(bad?" bad":"");n.hidden=false;clearTimeout(n._timer);n._timer=setTimeout(()=>{n.hidden=true},4200)}
async function api(path,init={}){if(!state.token)throw new Error("Connect with the agent token first.");const opts={...init,headers:{...(init.headers||{}),authorization:"Bearer "+state.token}};if(opts.body&&!opts.headers["content-type"])opts.headers["content-type"]="application/json";const res=await fetch(path,opts);let body={};try{body=await res.json()}catch{}if(!res.ok)throw new Error((body.error?.code?body.error.code+": ":"")+(body.error?.message||"Request failed"));return body}
async function recoveryApi(path,init={}){if(!state.recovery)throw new Error("Recovery token is required.");return api(path,{...init,headers:{...(init.headers||{}),"x-operator-recovery-token":state.recovery}})}
function badge(text,tone="neutral"){return '<span class="status '+tone+'">'+esc(text)+'</span>'}
function taskTone(s){return s==="VERIFIED"?"good":(["FAILED","CANCELLED"].includes(s)?"bad":(["BLOCKED","PAUSED"].includes(s)?"warn":"neutral"))}
function show(view){state.view=view;document.querySelectorAll(".view").forEach(n=>n.classList.toggle("active",n.id==="view-"+view));document.querySelectorAll(".nav").forEach(n=>{const active=n.dataset.view===view;n.classList.toggle("active",active);if(active)n.setAttribute("aria-current","page");else n.removeAttribute("aria-current")});loadView(view).catch(e=>toast(e.message,true));if(state.connected)api("/v1/control-center/experience",{method:"POST",body:JSON.stringify({event:"primary_view_opened"})}).catch(()=>{})}
async function connect(){state.token=$("agentToken").value.trim();state.recovery=$("recoveryToken").value.trim();if(!state.token)throw new Error("Agent token is required.");await api("/health");state.connected=true;$("connectionState").textContent="Connected";$("connectionState").className="status good";if(!state.onboardingStartedAt){state.onboardingStartedAt=Date.now();api("/v1/control-center/experience",{method:"POST",body:JSON.stringify({event:"onboarding_started"})}).catch(()=>{})}await loadView(state.view)}
async function loadHome(){const [overview,onboarding]=await Promise.all([api("/v1/control-center/overview"),api("/v1/control-center/onboarding")]);const cards=[["Active / running",(overview.tasks.states.RUNNING||0)+(overview.tasks.states.PENDING||0)],["Blocked",overview.tasks.states.BLOCKED||0],["Pending approvals",overview.approvals.pending||0],["Verified",overview.tasks.states.VERIFIED||0]];$("homeCards").innerHTML=cards.map(([label,value])=>'<div class="metric"><strong>'+esc(value)+'</strong><span>'+esc(label)+'</span></div>').join("");$("recentSessions").innerHTML=overview.tasks.recent.length?overview.tasks.recent.map(t=>'<div class="row"><div class="row-main"><div class="row-title">'+esc(t.userObjective)+'</div><div class="row-meta">'+esc(t.updatedAt)+'</div></div>'+badge(t.state,taskTone(t.state))+'</div>').join(""):'<div class="empty">No sessions yet.</div>';renderOnboarding(onboarding.model)}
function stepLabel(id){return ({INSTALL:"Install runtime",DOCTOR:"Doctor health check",AUTHENTICATE:"Authenticate",PAIR_DEVICE:"Pair device",CONFIGURE_ROOTS:"Choose authorized roots",READ_PROBE:"Verify read access",APPROVAL_PROBE:"Practice an approval",GUIDED_VERIFIED_TASK:"Complete a verified task"})[id]||id}
function renderOnboarding(model){let html=model.steps.map((s,i)=>'<div class="step '+s.status+'"><div class="step-dot">'+(s.status==="COMPLETE"?"✓":String(i+1))+'</div><div><div class="row-title">'+esc(stepLabel(s.id))+'</div><div class="row-meta">'+esc(s.status==="READY"?"Ready now":s.status==="COMPLETE"?"Complete":"Waiting for "+stepLabel(s.blockingStep))+'</div>'+(s.status==="READY"&&s.id==="READ_PROBE"?'<div class="actions"><button data-onboarding="read">Run safe read probe</button></div>':s.status==="READY"&&s.id==="APPROVAL_PROBE"?'<div class="actions"><button data-onboarding="approval">Create practice approval</button></div>':s.status==="READY"&&s.id==="GUIDED_VERIFIED_TASK"?'<div class="row-meta">Run any bounded task from ChatGPT or the task API and verify its outcome.</div>':"")+'</div></div>').join("");if(model.completed)html='<div class="diag"><strong>Onboarding complete.</strong><div class="row-meta">The runtime has evidence for the prepared-user journey.</div></div>'+html;$("onboarding").innerHTML=html;document.querySelectorAll("[data-onboarding]").forEach(b=>b.addEventListener("click",async()=>{try{if(b.dataset.onboarding==="read")await api("/v1/control-center/onboarding/read-probe",{method:"POST",body:"{}"});else await api("/v1/control-center/onboarding/approval-probe",{method:"POST",body:"{}"});await loadHome();if(b.dataset.onboarding==="approval")show("approvals")}catch(e){toast(e.message,true)}}));if(model.completed&&!state.onboardingCompletedSent&&state.onboardingStartedAt){state.onboardingCompletedSent=true;api("/v1/control-center/experience",{method:"POST",body:JSON.stringify({event:"onboarding_completed",durationMs:Date.now()-state.onboardingStartedAt})}).catch(()=>{})}}
async function loadSessions(){const [tasks,runtime]=await Promise.all([api("/v1/tasks?limit=100"),api("/v1/control-center/runtime?limit=100")]);const byId=new Map((runtime.projections||[]).map(p=>[p.active.id,p]));$("sessions").innerHTML=(tasks.tasks||[]).length?(tasks.tasks||[]).map(t=>{const p=byId.get(t.id)||{};const block=p.blocker?'<div class="row-meta"><strong>Needs attention:</strong> '+esc(p.blocker.reason)+'</div>':"";const verify=p.verification?'<div class="row-meta">Verification: '+esc(p.verification.state)+(p.reconciliationRequired?" · reconciliation required":"")+'</div>':"";return '<article class="card"><div class="row"><div class="row-main"><div class="row-title">'+esc(t.userObjective)+'</div><div class="row-meta mono">'+esc(t.id)+'</div>'+block+verify+'</div>'+badge(t.state,taskTone(t.state))+'</div></article>'}).join(""):'<div class="card empty">No sessions yet.</div>'}
async function loadApprovals(){const [a,r]=await Promise.all([api("/v1/control-center/approvals"),api("/v1/control-center/recovery")]);const items=[...(a.model.pending||[]),...(a.model.active||[])];$("approvals").innerHTML=items.length?items.map(x=>'<div class="row"><div class="row-main"><div class="row-title">'+esc(x.capability)+'</div><div class="row-meta">'+esc(x.reason)+'</div><div class="row-meta">Risk '+esc(x.risk)+' · '+esc(x.reversibility)+(x.secondsRemaining!==undefined?" · "+esc(x.secondsRemaining)+"s left":"")+'</div><div class="actions">'+(x.canApprove?'<button class="primary" data-approve="'+esc(x.actionId)+'" data-request="'+esc(x.approvalRequestId)+'">Approve once</button>':"")+(x.canDeny?'<button class="danger" data-deny="'+esc(x.actionId)+'" data-request="'+esc(x.approvalRequestId)+'">Deny</button>':"")+'</div></div>'+badge(x.status,x.status==="PENDING"?"warn":"neutral")+'</div>').join(""):'<div class="empty">No approval needs attention.</div>';$("recovery").innerHTML=(r.model.items||[]).length?r.model.items.map(x=>'<div class="row"><div class="row-main"><div class="row-title">'+esc(x.capability)+'</div><div class="row-meta">'+esc(x.reason)+'</div><div class="row-meta">Recommended: '+esc(x.recommendedAction)+(x.requiresFreshApproval?" · fresh approval required":"")+'</div></div>'+badge(x.disposition,x.disposition==="UNCERTAIN"?"warn":x.disposition==="TERMINAL"?"neutral":"good")+'</div>').join(""):'<div class="empty">No recovery items.</div>';document.querySelectorAll("[data-approve],[data-deny]").forEach(b=>b.addEventListener("click",async()=>{try{const decision=b.hasAttribute("data-approve")?"approve":"deny";await recoveryApi("/v1/approvals/"+encodeURIComponent(b.dataset.approve||b.dataset.deny),{method:"POST",body:JSON.stringify({decision,approvalRequestId:b.dataset.request})});toast(decision==="approve"?"Approved.":"Denied.");await loadApprovals();await loadHome()}catch(e){toast(e.message,true)}}))}
async function loadActivity(){const d=await api("/v1/activity?limit=150");$("activity").innerHTML=(d.events||[]).length?(d.events||[]).slice().reverse().map(e=>'<div class="card"><div class="row"><div class="row-main"><div class="row-title">'+esc(e.capability||e.type||"runtime event")+'</div><div class="row-meta">'+esc(e.timestamp||e.at||"")+(e.target?" · "+esc(e.target):"")+'</div></div>'+badge(e.result||e.status||"event",e.result==="failure"?"bad":e.result==="blocked"?"warn":e.result==="success"?"good":"neutral")+'</div></div>').join(""):'<div class="card empty">No activity recorded.</div>'}
async function loadDevices(){const d=await api("/v1/devices");const rows=[];if(d.local)rows.push({...d.local,status:"local"});for(const p of d.peers||[])rows.push(p);$("devices").innerHTML=rows.length?rows.map(x=>'<div class="card"><div class="row"><div class="row-main"><div class="row-title">'+esc(x.deviceName||"Device")+'</div><div class="row-meta mono">'+esc(x.fingerprint||x.deviceId||"")+'</div></div>'+badge(x.status||"known",x.status==="online"?"good":x.status==="revoked"?"bad":"neutral")+'</div></div>').join(""):'<div class="card empty">No device identity is available.</div>'}
async function loadPolicies(){const [s,p]=await Promise.all([api("/v1/settings"),api("/v1/enterprise-policy").catch(e=>({error:e.message}))]);$("policies").innerHTML='<article class="card"><h2>Local safety settings</h2><div class="code mono">'+esc(JSON.stringify(s.settings,null,2))+'</div></article><article class="card"><h2>Enterprise policy</h2><div class="code mono">'+esc(JSON.stringify(p.error?{configured:false,message:p.error}:p,null,2))+'</div></article>'}
async function loadKnowledge(){const [procedures,world]=await Promise.all([api("/v1/procedures?limit=50").catch(e=>({error:e.message})),api("/v1/world?limit=50").catch(e=>({error:e.message}))]);$("knowledge").innerHTML='<article class="card"><h2>Procedures</h2><div class="code mono">'+esc(JSON.stringify(procedures,null,2))+'</div></article><article class="card"><h2>World facts</h2><div class="code mono">'+esc(JSON.stringify(world,null,2))+'</div></article>'}
async function loadDiagnostics(){const d=await api("/v1/control-center/support-bundle");state.supportBundle=d.bundle;$("diagnostics").innerHTML=(d.bundle.diagnostics||[]).map(x=>'<div class="diag '+esc(x.severity)+'"><strong>'+esc(x.code)+'</strong><div class="row-meta">'+esc(x.message)+'</div><div class="row-meta"><strong>Repair:</strong> '+esc(x.repair)+'</div></div>').join("")+'<article class="card"><h2>Redacted support bundle</h2><div class="code mono">'+esc(JSON.stringify(d.bundle,null,2))+'</div></article>'}
async function loadView(v){if(!state.connected)return;if(v==="home")return loadHome();if(v==="sessions")return loadSessions();if(v==="approvals")return loadApprovals();if(v==="activity")return loadActivity();if(v==="devices")return loadDevices();if(v==="policies")return loadPolicies();if(v==="knowledge")return loadKnowledge();if(v==="diagnostics")return loadDiagnostics()}
document.querySelectorAll(".nav").forEach(n=>n.addEventListener("click",()=>show(n.dataset.view)));
document.querySelectorAll('[data-action="refresh"]').forEach(n=>n.addEventListener("click",()=>loadView(state.view).catch(e=>toast(e.message,true))));
$("connect").addEventListener("click",()=>connect().catch(e=>toast(e.message,true)));
$("approvalProbe").addEventListener("click",async()=>{try{await api("/v1/control-center/onboarding/approval-probe",{method:"POST",body:"{}"});toast("Practice approval created.");await loadApprovals()}catch(e){toast(e.message,true)}});
$("copyBundle").addEventListener("click",async()=>{try{if(!state.supportBundle)await loadDiagnostics();await navigator.clipboard.writeText(JSON.stringify(state.supportBundle,null,2));toast("Redacted support bundle copied.")}catch(e){toast("Copy failed: "+e.message,true)}});
})();